server:
  port: 9191

spring:
  application:
    name: backend-resources

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/ITM

keycloak:
  realm: ITM
  resource: backend-resources
  auth-server-url: http://localhost:8080
  credentials:
    secret: secret
